### PR TITLE
Simplify and clean up

### PR DESCRIPTION
**Pull request by tgutzler**
- Remove GetAttributes.vi from Singleton templates and use the DVR ref from GetInstance.vi
- Add MergeErrors
- Cosmetics

Saved as 2018. You'll have to do the save as previous, sorry

### CODE REVIEW

**Comment by MikaelHolmstrom** [comment]
I'm currently only doing work in the LV2020 branch, what LV version are you using?
I'll add these changes into the 2020 branch plus I'm going to update the GetInstance with a feedback node so if a DVR ref already been created and still valid, it won't go into the new VI at all.

**Comment by MikaelHolmstrom** [comment]
I might do some small changes...
1) Replace all Error in/out to the NXG style without the text "...(no error)".
2) Make the VI's FP a bit taller so it's easier to start adding Controls and indicators to it.
Thoughts?

**Comment by tgutzler** [comment]
I'm on 2018, hopefully weeks away from 2020. Just started testing the builds. Not touching NXG though
I like the change to GetInstance.
Don't mind the old 3D error in, it takes less realestate and I'm already using it in 500000 other vis. I support the removal of "(no error") in the label.
The front-panel size is coming out of a quickdrop that I use, which aligns the controls with the connector pane and at the same resizes the FP to fit. When I add new controls, I usually do it from the BD and then just run the quickdrop once when I'm done. So, if you want to make the FP larger, go ahead :) You probably know better what your "clients" want

**Comment by MikaelHolmstrom** [comment]
Welcome to 2020 (soon).
I always start adding items on the FP and then go to the BD :-)
As you know NXG has been killed, but I do like the controls. Wonder if they will rename the palette soon ;-)
BTW I use the same type of QD shortcut VI to align controls, if you can share your version, do you mind sending me your copy.

**Pull request closed without merging**
